/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardRouteImport } from './routes/onboard/route'
import { Route as IndexImport } from './routes/index'
import { Route as OnboardIndexImport } from './routes/onboard/index'

// Create/Update Routes

const OnboardRouteRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardIndexRoute = OnboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/onboard/': {
      id: '/onboard/'
      path: '/'
      fullPath: '/onboard/'
      preLoaderRoute: typeof OnboardIndexImport
      parentRoute: typeof OnboardRouteImport
    }
  }
}

// Create and export the route tree

interface OnboardRouteRouteChildren {
  OnboardIndexRoute: typeof OnboardIndexRoute
}

const OnboardRouteRouteChildren: OnboardRouteRouteChildren = {
  OnboardIndexRoute: OnboardIndexRoute,
}

const OnboardRouteRouteWithChildren = OnboardRouteRoute._addFileChildren(
  OnboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboard': typeof OnboardRouteRouteWithChildren
  '/onboard/': typeof OnboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboard': typeof OnboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/onboard': typeof OnboardRouteRouteWithChildren
  '/onboard/': typeof OnboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/onboard' | '/onboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onboard'
  id: '__root__' | '/' | '/onboard' | '/onboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardRouteRoute: typeof OnboardRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardRouteRoute: OnboardRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/onboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/onboard": {
      "filePath": "onboard/route.tsx",
      "children": [
        "/onboard/"
      ]
    },
    "/onboard/": {
      "filePath": "onboard/index.tsx",
      "parent": "/onboard"
    }
  }
}
ROUTE_MANIFEST_END */
