/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardRouteImport } from './routes/onboard/route'
import { Route as HomeRouteImport } from './routes/home/route'
import { Route as IndexImport } from './routes/index'
import { Route as OnboardIndexImport } from './routes/onboard/index'
import { Route as HomeIndexImport } from './routes/home/index'
import { Route as OnboardLoginImport } from './routes/onboard/login'
import { Route as OnboardConfirmImport } from './routes/onboard/confirm'
import { Route as HomeSettingsImport } from './routes/home/settings'

// Create/Update Routes

const OnboardRouteRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRoute,
} as any)

const HomeRouteRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardIndexRoute = OnboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardRouteRoute,
} as any)

const HomeIndexRoute = HomeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRouteRoute,
} as any)

const OnboardLoginRoute = OnboardLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => OnboardRouteRoute,
} as any)

const OnboardConfirmRoute = OnboardConfirmImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => OnboardRouteRoute,
} as any)

const HomeSettingsRoute = HomeSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HomeRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRoute
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/home/settings': {
      id: '/home/settings'
      path: '/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsImport
      parentRoute: typeof HomeRouteImport
    }
    '/onboard/confirm': {
      id: '/onboard/confirm'
      path: '/confirm'
      fullPath: '/onboard/confirm'
      preLoaderRoute: typeof OnboardConfirmImport
      parentRoute: typeof OnboardRouteImport
    }
    '/onboard/login': {
      id: '/onboard/login'
      path: '/login'
      fullPath: '/onboard/login'
      preLoaderRoute: typeof OnboardLoginImport
      parentRoute: typeof OnboardRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof HomeRouteImport
    }
    '/onboard/': {
      id: '/onboard/'
      path: '/'
      fullPath: '/onboard/'
      preLoaderRoute: typeof OnboardIndexImport
      parentRoute: typeof OnboardRouteImport
    }
  }
}

// Create and export the route tree

interface HomeRouteRouteChildren {
  HomeSettingsRoute: typeof HomeSettingsRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteRouteChildren: HomeRouteRouteChildren = {
  HomeSettingsRoute: HomeSettingsRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteRouteWithChildren = HomeRouteRoute._addFileChildren(
  HomeRouteRouteChildren,
)

interface OnboardRouteRouteChildren {
  OnboardConfirmRoute: typeof OnboardConfirmRoute
  OnboardLoginRoute: typeof OnboardLoginRoute
  OnboardIndexRoute: typeof OnboardIndexRoute
}

const OnboardRouteRouteChildren: OnboardRouteRouteChildren = {
  OnboardConfirmRoute: OnboardConfirmRoute,
  OnboardLoginRoute: OnboardLoginRoute,
  OnboardIndexRoute: OnboardIndexRoute,
}

const OnboardRouteRouteWithChildren = OnboardRouteRoute._addFileChildren(
  OnboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/onboard': typeof OnboardRouteRouteWithChildren
  '/home/settings': typeof HomeSettingsRoute
  '/onboard/confirm': typeof OnboardConfirmRoute
  '/onboard/login': typeof OnboardLoginRoute
  '/home/': typeof HomeIndexRoute
  '/onboard/': typeof OnboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home/settings': typeof HomeSettingsRoute
  '/onboard/confirm': typeof OnboardConfirmRoute
  '/onboard/login': typeof OnboardLoginRoute
  '/home': typeof HomeIndexRoute
  '/onboard': typeof OnboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRouteWithChildren
  '/onboard': typeof OnboardRouteRouteWithChildren
  '/home/settings': typeof HomeSettingsRoute
  '/onboard/confirm': typeof OnboardConfirmRoute
  '/onboard/login': typeof OnboardLoginRoute
  '/home/': typeof HomeIndexRoute
  '/onboard/': typeof OnboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/onboard'
    | '/home/settings'
    | '/onboard/confirm'
    | '/onboard/login'
    | '/home/'
    | '/onboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home/settings'
    | '/onboard/confirm'
    | '/onboard/login'
    | '/home'
    | '/onboard'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/onboard'
    | '/home/settings'
    | '/onboard/confirm'
    | '/onboard/login'
    | '/home/'
    | '/onboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRouteRoute: typeof HomeRouteRouteWithChildren
  OnboardRouteRoute: typeof OnboardRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRouteRoute: HomeRouteRouteWithChildren,
  OnboardRouteRoute: OnboardRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/home",
        "/onboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/home": {
      "filePath": "home/route.tsx",
      "children": [
        "/home/settings",
        "/home/"
      ]
    },
    "/onboard": {
      "filePath": "onboard/route.tsx",
      "children": [
        "/onboard/confirm",
        "/onboard/login",
        "/onboard/"
      ]
    },
    "/home/settings": {
      "filePath": "home/settings.tsx",
      "parent": "/home"
    },
    "/onboard/confirm": {
      "filePath": "onboard/confirm.tsx",
      "parent": "/onboard"
    },
    "/onboard/login": {
      "filePath": "onboard/login.tsx",
      "parent": "/onboard"
    },
    "/home/": {
      "filePath": "home/index.tsx",
      "parent": "/home"
    },
    "/onboard/": {
      "filePath": "onboard/index.tsx",
      "parent": "/onboard"
    }
  }
}
ROUTE_MANIFEST_END */
